### ISSUE TITLE
Using require instead of import

### ISSUE THREAD

**Issue by hrudelius** [fhqvst/nordnet#1]
Hi,

I'm trying to get the nordnet wrapper to work, using the provided example code. As my environment doesn't seem to support 'import' I try to use 'require' instead. However I can't get it to work (although it worked on the Avanza library). Here is the code I'm using:

`//import Nordnet from 'nordnet'
//const nordnet = new Nordnet()

const Nordnet = require('Nordnet');
nordnet = new Nordnet()
`
This is the error I'm getting:

TypeError: Nordnet is not a constructor
    at Object.<anonymous> (c:\Users\hakan\node\nordnetApi\app.js:5:11)
    at Module._compile (module.js:566:14)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

Guess there is no need to say I'm a beginner at Node and js...

**Comment by hrudelius** [comment]
After two hours of googling and experimenting I solved it. "Babel assigns default exports to the default property. So if you use require to import ES6 modules, you need to access the default property:"

So the code should be:

`var Nordnet = require('Nordnet').default;
nordnet = new Nordnet()`
